Handle return code

diff --git a/api b/api
--- a/api
+++ b/api
@@ -11,100 +11,107 @@ _request() {
   local api_error
 
   response=$(eval "$command") \
-  || ERROR "Curl return code is $?:\n" "$command" \
-  || return 1
+  || ERROR "Curl return code is $? for command:\n" "$command" \
+  || return $?
 
   api_error=$(jq -r 'if type =="object" and has("error") then .error else empty end' <<< "$response") \
   && test ! "$api_error" \
   || ERROR 'TestRail API returns error:\n' "$api_error" \
-  || return 2
+  || return $?
 
   jq -c '.' <<< "$response" \
   || ERROR "Response is not a json:" "$response" \
-  || return 3
+  || return $?
 }
 
 get_case() {
   local id=${1:?Case ID is required}
   _request "get_case/${id}" \
   || ERROR "Couldn't get case with ID $id"
+  return $?
 }
 
 update_case() {
   local id=${1:?Case ID is required}
   local case=${2:?Test case is required}
   _request "update_case/${id}" -X POST -d "'$case'" \
-  || ERROR "Couldn't update case with ID $id:\n" "$case"
+  || ERROR "Couldn't update case with ID $id:\n" "$case" \
+  || return $?
 }
 
 get_test() {
   local test_id=${1:?Test ID is required}
   _request "get_test/${test_id}" \
-  || ERROR "Couldn't get test with ID $test_id"
+  || ERROR "Couldn't get test with ID $test_id" \
+  || return $?
 }
 
 get_cases_from_section() {
-  local section_id=${1:?Section ID is required}
-  local suite
-  local project
-  suite="$(./api get_section "$section_id" | jq -r '.suite_id')" \
-  && test "$suite" \
-  && project="$(get_suite "$suite" | jq -r '.project_id')" \
-  && test "$project" \
-  && _request "get_cases/${project}&suite_id=${suite}&section_id=${section_id}" \
-  || ERROR "Couldn't get cases for section ID $section_id"
+  local project=${1:?Project ID is required}
+  local suite=${2:?Suite ID is required}
+  local section_id=${3:?Section ID is required}
+  _request "get_cases/${project}&suite_id=${suite}&section_id=${section_id}" \
+  || ERROR "Couldn't get cases for section ID $section_id" \
+  || return $?
 }
 
 get_results() {
   local test=${1:?Test ID is required}
   _request "get_results/${test}" \
-  || ERROR "Couldn't get result for test $test"
+  || ERROR "Couldn't get result for test $test" \
+  || return $?
 }
 
 get_results_for_run() {
   local run_id=${1:?Run ID is required}
   _request "get_results_for_run/${run_id}" \
-  || ERROR "Couldn't get result for run $run_id"
+  || ERROR "Couldn't get result for run $run_id" \
+  || return $?
 }
 
 get_results_for_case() {
   local run=${1:?Run ID is required}
   local case=${2:?Case ID is required}
   _request "get_results_for_case/${run}/${case}" \
-  || ERROR "Couldn't get results for run $run and case $case"
+  || ERROR "Couldn't get results for run $run and case $case" \
+  || return $?
 }
 
 get_suite() {
   local suite_id=${1:?Suite ID is required}
   _request "get_suite/${suite_id}" \
-  || ERROR "Couldn't get suite $suite_id"
+  || ERROR "Couldn't get suite $suite_id" \
+  || return $?
 }
 
 get_section() {
   local section_id=${1:?Section ID is required}
   _request "get_section/${section_id}" \
-  || ERROR "Couldn't get section $section_id"
+  || ERROR "Couldn't get section $section_id" \
+  || return $?
 }
 
 get_sections() {
-  local \
-    project=${1:?Project ID is required} \
-    suite=${2:?Suite ID is required}
+  local project=${1:?Project ID is required}
+  local suite=${2:?Suite ID is required}
   _request "get_sections/${project}&suite_id=${suite}" \
-  || ERROR "Couldn't get sections for $project project and $suite suite"
+  || ERROR "Couldn't get sections for $project project and $suite suite" \
+  || return $?
 }
 
 update_section() {
   local id=${1:?Section ID is required}
   local body=${2:?Section body is required}
   _request "update_section/${id}" -X POST -d "$body" \
-  || ERROR "Couldn't update section with ID $id"
+  || ERROR "Couldn't update section with ID $id" \
+  || return $?
 }
 
 delete_section() {
   local id=${1:?Section ID is required}
   _request "delete_section/${id}" -X POST \
-  || ERROR "Couldn't update section with ID $id"
+  || ERROR "Couldn't update section with ID $id" \
+  || return $?
 }
 
 eval "$*"
